# Container image that runs your code
FROM alpine:3.10

# Copies your code file from your action repository to the filesystem path `/` of the container
COPY npmVersionBumper.sh /npmVersionBumper.sh

# Code file to execute when the docker container starts up (`npmVersionBumper.sh`)
ENTRYPOINT ["/npmVersionBumper.sh"]